== [#print]#PRINT##, P.

A statement which writes the internal form of a value out to a data file.

[source,console]
----
PRINT#E,A,B,C,D$,E$,F$
PRINT#4,prn$
----

The format of the variables as written to the file differs from the format used on the BBC Micro. All numeric values are written as five bytes of binary real data (see the Annex entitled link:annexd.html[Format of Program and Variables in Memory]). Strings are written as the bytes in the string (in the correct order) plus a carriage return.

Before you use this statement, you must normally have opened a file using link:bbckey3.html#openout[OPENOUT] or link:bbckey3.html#openup[OPENUP]. PRINT# may alternatively be used with the AUX device (usually a serial port), which has the 'permanently open' handle = 3, or the PRN device (usually a parallel port) which has the 'permanently open' handle = 4.

You can use PRINT# to write data (numbers and strings) to a data file in the 'standard' manner. If you wish to 'pack' your data in a different way, you should use link:bbckey1.html#bput[BPUT#]. You can use PRINT# and BPUT# together to mix or modify the data format. For example, if you wish to write a 'compatible' text file, you could PRINT# the string and BPUT# a line-feed. This would write the string followed by a carriage-return and a line-feed to the file.

Remember, with BBC BASIC (Z80) the format of the file is completely under your control.

=== Syntax

[source,console]
----
PRINT#<numeric>{,<numeric>|<str>}
----

=== Associated Keywords

[source,console]
----
PRINT, OPENUP, OPENOUT, CLOSE#, INPUT#, BPUT#, BGET#,  EXT#, PTR#, EOF#
----

