== [#tab]#TAB#

A keyword available in link:bbckey3.html#print[PRINT] or link:bbckey2.html#input[INPUT].

There are two versions of TAB: TAB(X) and TAB(X,Y) and they are effectively two different keywords.

TAB(X) is a printer orientated statement. The number of printable characters since the last new-line (link:bbckey1.html#count[COUNT]) is compared with X. If X is equal or greater than COUNT, sufficient spaces to make them equal are printed. These spaces will overwrite any characters which may already be on the screen. If X is less than COUNT, a new-line will be printed first.

TAB(X,Y) is a screen orientated statement. It will move the cursor on the screen to character cell X,Y (column X, row Y) if possible. No characters are overwritten and COUNT is NOT updated. Consequently, a TAB(X,Y) followed by a TAB(X) will give unpredictable (at first glance) results.

The leftmost column is column 0 and the top of the screen is row 0.

[source,console]
----
PRINT TAB(10);A$
PRINT TAB(X,Y);B$
----

=== Syntax

[source,console]
----
PRINT TAB(<numeric>[,<numeric>])
INPUT TAB(<numeric>[,<numeric>])
----

=== Associated Keywords

[source,console]
----
POS, VPOS, PRINT, INPUT
----

