== Operating System Interface

=== [#introduction]#Introduction#

As with the BBC micro computer, the star (*) commands provide access to the operating system. 

For the most part, the MOS is transparent to BASIC; most of the operations via the MOS and VDP are accessed via normal BBC BASIC statements, with the following exceptions:

==== link:#accessing-the-mos-system-variables[]Accessing the MOS system variables

MOS has a small system variables area which is in an area of RAM outside of its 64K segment. To access these, you will need to do an OSBYTE call

Example: Print the least significant byte of the internal clock counter

[source,notranslate]
----
10 L%=&00 : REM The system variable to fetch
20 A%=&A0 : REM The OSBYTE number
30 PRINT USR(&FFF4)
----

For a full list of system variables, please refer to https://github.com/breakintoprogram/agon-mos/blob/main/src/mos_api.inc[mos_api.inc].

'''''

=== [#accessing]#Accessing Star Commands#

The star commands may be accessed directly or via the link:bbckey3.html#oscli[OSCLI] statement. The two examples below both access the link:opsys1.html#bye[BYE] command.

[source,console]
----
*BYE

OSCLI("BYE")
----

==== [#syntax]#Syntax#

A star command must be the last (or only) command on a program line and its argument may not be a variable. If you need to use one of these commands with a variable as the argument, use the link:bbckey3.html#oscli[OSCLI] statement. Examples of the use of the OSCLI statement are given below in the link:opsys1.html[Resident Star Commands] sub-section.

==== [#case]#Case Conversion#

Star commands and their associated qualifiers are converted from lower-case to upper-case if necessary. For example, \*era wombat is converted to \*ERA WOMBAT. 

==== [#special]#Special Characters#

Control characters, lower-case characters, DEL and quotation marks may be incorporated in filenames by using the 'escape' character '|'.

[cols=",",]
|===
|\|A   |gives ^A.
|\|a |gives lower-case A.
|\|? |gives Del.
|\|" |gives the quote marks ".
|\|\| |gives the escape character \|.
|\|! |sets bit 7 of the following character.
|===

==== link:#running-star-commands-with-variables[]Running star commands with variables

The star command parser does not use the same evaluator as BBC BASIC, so whilst commands can be run in BASIC, variable names are treated as literals.

Example: This will not work

[source,console]
----
10 INPUT "Filename";f$
20 INPUT "Load Address";addr%
30 *LOAD f$ addr%
----

To do this correctly, you must call the star command indirectly using the OSCLI command

Example: This will work

[source,console]
----
30 OSCLI("LOAD " + f$ + " " + STR$(addr%)) 
----

