== R. T. RUSSELL

=== BBC BASIC (Z80) Manual

== Table of Contents

. *link:bbc1.html[Introduction]*
.. link:bbc1.html#beforestart[Before You Start]
... link:bbc1.html#requirements[System Requirements]
... link:bbc1.html#technicalities[Technicalities]
... link:bbc1.html#configuration[Configuration]
.. link:bbc1.html#running[Running BBC BASIC (Z80)]
. *link:bbc2.html[General Information]*
.. link:bbc2.html#introduction[Introduction]
... link:bbc2.html#linenumbers[Line Numbers]
... link:bbc2.html#separators[Statement Separators]
.. link:bbc2.html#editing[The Line Editor]
.. link:bbc2.html#expression[Expression Priority]
... link:bbc2.html#evaluation[Order of Evaluation]
... link:bbc2.html#examples[Examples]
.. link:bbc2.html#variables[Variables]
... link:bbc2.html#specification[Specification]
... link:bbc2.html#numeric[Numeric Variables]
.... link:bbc2.html#real[Real Variables]
.... link:bbc2.html#integer[Integer Variables]
.... link:bbc2.html#static[Static Variables]
.... link:bbc2.html#boolean[Boolean Variables]
.... link:bbc2.html#accuracy[Numeric Accuracy]
... link:bbc2.html#stringsetc[String Variables and Garbage]
.... link:bbc2.html#strings[Strings]
.... link:bbc2.html#garbage[Garbage Generation]
.... link:bbc2.html#memory[Memory Allocation]
... link:bbc2.html#arrays[Arrays]
.. link:bbc2.html#programflow[Program Flow Control]
... link:bbc2.html#flowintro[Introduction]
... link:bbc2.html#looperrors[Loop Operation Errors]
... link:bbc2.html#structure[Program Structure Limitations]
... link:bbc2.html#leavingloops[Leaving Program Loops]
.... link:bbc2.html#repeatuntil[REPEAT...UNTIL Loops]
.... link:bbc2.html#changing[Changing the Loop Variable]
.... link:bbc2.html#popping[Popping the Inner Variable]
... link:bbc2.html#localstack[Local Variables]
... link:bbc2.html#stack[Stack Pointer]
.. link:bbc2.html#indirection[Indirection]
... link:bbc2.html#indirintro[Introduction]
... link:bbc2.html#query[Query]
.... link:bbc2.html#byte[Byte Access]
.... link:bbc2.html#bytequery[Query as a Byte Variable]
... link:bbc2.html#exclamation[Exclamation]
... link:bbc2.html#dollar[Dollar]
... link:bbc2.html#binaryoperators[Use as Binary Operators]
... link:bbc2.html#powerofindirection[Power of Indirection Operators]
.. link:bbc2.html#operators[Operators and Special Symbols]
.. link:bbc2.html#keywords[Keywords]
.. link:bbc2.html#errorhandling[Error Handling]
... link:bbc2.html#errorintro[Introduction]
.... link:bbc2.html#errortypes[Types of Errors]
.... link:bbc2.html#trapping[Trapping Errors]
.... link:bbc2.html#reasons[Reasons for Trapping Errors]
... link:bbc2.html#errortrapping[Error Trapping Commands]
... link:bbc2.html#errorreporting[Error Reporting]
.... link:bbc2.html#err[ERR]
.... link:bbc2.html#erl[ERL]
.... link:bbc2.html#report[REPORT]
... link:bbc2.html#errorexamples[Error Trapping Examples]
.. link:bbc2.html#procedures[Procedures and Functions]
... link:bbc2.html#procintro[Introduction]
... link:bbc2.html#names[Names]
... link:bbc2.html#definitions[Functions and Procedure Definitions]
.... link:bbc2.html#starting[Starting a Definition]
.... link:bbc2.html#body[The Function/Procedure Body]
.... link:bbc2.html#ending[Ending a Definition]
.... link:bbc2.html#singleline[Single Line Functions/Procedures]
.... link:bbc2.html#extending[Extending the Language]
... link:bbc2.html#parameters[Passing Parameters]
.... link:bbc2.html#formalactual[Formal and Actual Parameters]
... link:bbc2.html#localvariables[Local Variables]
.... link:bbc2.html#reentrant[Re-entrant Functions/Procedures]
. *link:bbc3.html[Assembler]*
.. link:bbc3.html#introduction[Introduction]
... link:bbc3.html#mnemonics[Instruction mnemonics]
... link:bbc3.html#statements[Statements]
... link:bbc3.html#labels[Labels]
... link:bbc3.html#comments[Comments]
... link:bbc3.html#constants[Constants]
.... link:bbc3.html#byte[Define Byte - DEFB]
.... link:bbc3.html#word[Define Word - DEFW]
.... link:bbc3.html#defm[Define Message - DEFM]
.. link:bbc3.html#reserving[Reserving Memory]
... link:bbc3.html#programcounter[The Program Counter]
... link:bbc3.html#usingdim[Using DIM to Reserve Memory]
... link:bbc3.html#movinghimem[Moving HIMEM to Reserve Memory]
... link:bbc3.html#length[Length of Reserved Memory]
... link:bbc3.html#initial[Initial Setting of the Program Counter]
.. link:bbc3.html#process[The Assembly Process]
... link:bbc3.html#opt[OPT]
... link:bbc3.html#different[Assembly at a Different Address]
... link:bbc3.html#summary[OPT Summary]
.... link:bbc3.html#codeatp[Code Assembled Starting at P%]
.... link:bbc3.html#codeato[Code Assembled Starting at O%]
... link:bbc3.html#how[How the Assembler Works]
... link:bbc3.html#saveload[Saving and Loading Machine Code Programs]
.... link:bbc3.html#save[*SAVE]
.... link:bbc3.html#load[*LOAD]
.. link:bbc3.html#condmacro[Conditional Assembly and Macros]
... link:bbc3.html#condintro[Introduction]
... link:bbc3.html#conditional[Conditional Assembly]
... link:bbc3.html#macros[Macros]
. *link:bbckey0.html[Statements and Functions]*
.. link:bbckey0.html#introduction[Introduction]
.. link:bbckey0.html#syntax[Syntax]
.. link:bbckey0.html#symbols[Symbols]
.. link:bbckey1.html#abs[ABS]
.. link:bbckey1.html#acs[ACS]
.. link:bbckey1.html#adval[ADVAL]
.. link:bbckey1.html#and[AND]
.. link:bbckey1.html#asc[ASC]
.. link:bbckey1.html#asn[ASN]
.. link:bbckey1.html#atn[ATN]
.. link:bbckey1.html#auto[AUTO]
.. link:bbckey1.html#bget[BGET#]
.. link:bbckey1.html#bput[BPUT#]
.. link:bbckey1.html#call[CALL]
... link:bbckey1.html#callparms[Parameter Table]
... link:bbckey1.html#callformats[Parameter Formats]
.. link:bbckey1.html#chain[CHAIN]
.. link:bbckey1.html#chr[CHR$]
.. link:bbckey1.html#clear[CLEAR]
.. link:bbckey1.html#close[CLOSE#]
.. link:bbckey1.html#clg[CLG]
.. link:bbckey1.html#cls[CLS]
.. link:bbckey1.html#colour[COLOUR]
.. link:bbckey1.html#cos[COS]
.. link:bbckey1.html#count[COUNT]
.. link:bbckey1.html#data[DATA]
.. link:bbckey1.html#def[DEF]
.. link:bbckey1.html#deg[DEG]
.. link:bbckey1.html#delete[DELETE]
.. link:bbckey1.html#dim[DIM]
... link:bbckey1.html#dimarrays[Dimensioning Arrays]
... link:bbckey1.html#dimreserving[Reserving an Area of Memory]
.. link:bbckey1.html#div[DIV]
.. link:bbckey1.html#draw[DRAW]
.. link:bbckey1.html#edit[EDIT]
.. link:bbckey1.html#else[ELSE]
.. link:bbckey1.html#end[END]
.. link:bbckey1.html#endproc[ENDPROC]
.. link:bbckey1.html#envelope[ENVELOPE]
.. link:bbckey2.html#eof[EOF#]
.. link:bbckey2.html#eor[EOR]
.. link:bbckey2.html#erl[ERL]
.. link:bbckey2.html#err[ERR]
.. link:bbckey2.html#eval[EVAL]
.. link:bbckey2.html#exp[EXP]
.. link:bbckey2.html#ext[EXT#]
.. link:bbckey2.html#false[FALSE]
.. link:bbckey2.html#fn[FN]
.. link:bbckey2.html#for[FOR]
.. link:bbckey2.html#gcol[GCOL]
.. link:bbckey2.html#get[GET/GET$]
.. link:bbckey2.html#gosub[GOSUB]
.. link:bbckey2.html#goto[GOTO]
.. link:bbckey2.html#himem[HIMEM]
.. link:bbckey2.html#if[IF]
.. link:bbckey2.html#inkey[INKEY/INKEY$]
.. link:bbckey2.html#input[INPUT]
.. link:bbckey2.html#inputline[INPUT LINE]
.. link:bbckey2.html#inputhash[INPUT#]
.. link:bbckey2.html#instr[INSTR]
.. link:bbckey2.html#int[INT]
.. link:bbckey2.html#left[LEFT$]
.. link:bbckey2.html#len[LEN]
.. link:bbckey2.html#let[LET]
.. link:bbckey2.html#list[LIST]
.. link:bbckey2.html#listif[LIST IF]
... link:bbckey2.html#limitations[Limitations]
.. link:bbckey2.html#listo[LISTO]
... link:bbckey2.html#settings[Bit Settings]
.. link:bbckey2.html#ln[LN]
.. link:bbckey2.html#load[LOAD]
.. link:bbckey2.html#local[LOCAL]
.. link:bbckey2.html#log[LOG]
.. link:bbckey2.html#lomem[LOMEM]
.. link:bbckey3.html#mid[MID$]
.. link:bbckey3.html#mod[MOD]
.. link:bbckey3.html#mode[MODE]
.. link:bbckey3.html#move[MOVE]
.. link:bbckey3.html#new[NEW]
.. link:bbckey3.html#next[NEXT]
.. link:bbckey3.html#not[NOT]
.. link:bbckey3.html#old[OLD]
.. link:bbckey3.html#on[ON]
... link:bbckey3.html#limitations[Limitations]
.. link:bbckey3.html#onerror[ON ERROR]
.. link:bbckey3.html#openin[OPENIN]
.. link:bbckey3.html#openout[OPENOUT]
.. link:bbckey3.html#openup[OPENUP]
.. link:bbckey3.html#opt[OPT]
... link:bbckey3.html#codeatp[Code Assembled Starting at P%]
... link:bbckey3.html#codeato[Code Assembled Starting at O%]
.. link:bbckey3.html#or[OR]
.. link:bbckey3.html#oscli[OSCLI]
.. link:bbckey3.html#page[PAGE]
.. link:bbckey3.html#pi[PI]
.. link:bbckey3.html#plot[PLOT]
.. link:bbckey3.html#point[POINT]
.. link:bbckey3.html#pos[POS]
.. link:bbckey3.html#print[PRINT]
... link:bbckey3.html#printinfo[General Information]
... link:bbckey3.html#printformat[Print Format Control]
.... link:bbckey3.html#strformat[STR$ Format Control - SS]
.... link:bbckey3.html#formatsel[Format Selection - NN]
.... link:bbckey3.html#numdig[Number of Digits - PP]
.... link:bbckey3.html#zonewidth[Zone Width - WW]
.... link:bbckey3.html#changingat[Changing the Print Control Variable]
... link:bbckey3.html#printeg[Examples]
.. link:bbckey4.html#print[PRINT#]
.. link:bbckey4.html#proc[PROC]
.. link:bbckey4.html#ptr[PTR#]
.. link:bbckey4.html#put[PUT]
.. link:bbckey4.html#rad[RAD]
.. link:bbckey4.html#read[READ]
.. link:bbckey4.html#rem[REM]
.. link:bbckey4.html#renumber[RENUMBER]
.. link:bbckey4.html#repeat[REPEAT]
.. link:bbckey4.html#report[REPORT]
.. link:bbckey4.html#restore[RESTORE]
.. link:bbckey4.html#return[RETURN]
.. link:bbckey4.html#right[RIGHT$]
.. link:bbckey4.html#rnd[RND]
.. link:bbckey4.html#run[RUN]
.. link:bbckey4.html#save[SAVE]
.. link:bbckey4.html#sgn[SGN]
.. link:bbckey4.html#sin[SIN]
.. link:bbckey4.html#sound[SOUND]
.. link:bbckey4.html#spc[SPC]
.. link:bbckey4.html#sqr[SQR]
.. link:bbckey4.html#step[STEP]
.. link:bbckey4.html#stop[STOP]
.. link:bbckey4.html#str[STR$]
.. link:bbckey4.html#string[STRING$]
.. link:bbckey4.html#tab[TAB]
.. link:bbckey4.html#tan[TAN]
.. link:bbckey4.html#then[THEN]
.. link:bbckey4.html#time[TIME]
.. link:bbckey4.html#to[TO]
.. link:bbckey4.html#top[TOP]
.. link:bbckey4.html#trace[TRACE]
.. link:bbckey4.html#true[TRUE]
.. link:bbckey4.html#until[UNTIL]
.. link:bbckey4.html#usr[USR]
.. link:bbckey4.html#val[VAL]
.. link:bbckey4.html#vdu[VDU]
.. link:bbckey4.html#vpos[VPOS]
.. link:bbckey4.html#width[WIDTH]
. *link:opsys0.html[Operating System Interface]*
.. link:opsys0.html#introduction[Introduction]
... link:opsys0.html#specifiers[File Specifiers]
... link:opsys0.html#symbols[Symbols]
.. link:opsys0.html#accessing[Accessing Star Commands]
... link:opsys0.html#syntax[Syntax]
... link:opsys0.html#case[Case Conversion]
... link:opsys0.html#special[Special Characters]
.. link:opsys1.html#resident[Resident Star Commands]
... link:opsys1.html#bye[*BYE]
... link:opsys1.html#cpm[*CPM]
... link:opsys1.html#dir[*DIR]
... link:opsys1.html#drive[*DRIVE]
... link:opsys1.html#erase[*ERA]
... link:opsys1.html#load[*LOAD]
... link:opsys1.html#opt[*OPT]
... link:opsys1.html#rename[*REN]
... link:opsys1.html#reset[*RESET]
... link:opsys1.html#save[*SAVE]
... link:opsys1.html#type[*TYPE]
. *link:bbcfile1.html[BBC BASIC (Z80) Disk Files]*
.. link:bbcfile1.html#introduction[Introduction]
.. link:bbcfile1.html#structure[The Structure of Files]
... link:bbcfile1.html#basics[Basics]
... link:bbcfile1.html#serial[Serial (Sequential) Files]
... link:bbcfile1.html#random[Random Access Files]
... link:bbcfile1.html#indexed[Indexed Files]
.. link:bbcfile1.html#bbcfiles[Files in BBC BASIC (Z80)]
... link:bbcfile1.html#bbcintro[Introduction]
... link:bbcfile1.html#howdata[How Data is Read/Written]
... link:bbcfile1.html#howstored[How Data is Stored]
.... link:bbcfile1.html#numeric[Numeric Data]
.... link:bbcfile1.html#strings[How Strings are Stored]
... link:bbcfile1.html#referred[How Files are Referred To]
... link:bbcfile1.html#buffering[File Buffering]
.. link:bbcfile1.html#commands[Disk File Commands]
... link:bbcfile1.html#commandintro[Introduction]
... link:bbcfile1.html#filenames[Filenames]
... link:bbcfile1.html#organisation[Organisation of Examples]
... link:bbcfile1.html#manipulation[Program File Manipulation]
.... link:bbcfile1.html#save[SAVE]
.... link:bbcfile1.html#load[LOAD]
.... link:bbcfile1.html#chain[CHAIN]
.... link:bbcfile1.html#merge[MERGE]
.... link:bbcfile1.html#delete[*ERA]
.... link:bbcfile1.html#rename[*REN]
.... link:bbcfile1.html#dir[*DIR]
... link:bbcfile1.html#datafiles[Disk Data Files]
.... link:bbcfile1.html#dataintro[Introduction]
.... link:bbcfile1.html#opening[Opening Files]
.... link:bbcfile1.html#functions[File Opening Functions]
.... link:bbcfile1.html#openout[OPENOUT]
.... link:bbcfile1.html#openin[OPENIN]
.... link:bbcfile1.html#openup[OPENUP]
.... link:bbcfile1.html#close[CLOSE#]
.... link:bbcfile1.html#input[INPUT#]
.... link:bbcfile1.html#print[PRINT#]
.... link:bbcfile1.html#ext[EXT#]
.... link:bbcfile1.html#ptr[PTR#]
.... link:bbcfile1.html#eof[EOF#]
.... link:bbcfile1.html#bget[BGET#]
.... link:bbcfile1.html#bput[BPUT#]
.. link:bbcfile2.html#serialfiles[Serial Files]
... link:bbcfile2.html#introduction[Introduction]
... link:bbcfile2.html#characterfiles[Character Data Files]
.... link:bbcfile2.html#example1[Ex 1 - Writing Serial Character Data]
.... link:bbcfile2.html#example2[Ex 2 - Reading Serial Character Data]
.... link:bbcfile2.html#example3[Ex 3 - Writing 'AT END' of Character Files]
... link:bbcfile2.html#mixedfiles[Mixed Numeric/Character Data Files]
.... link:bbcfile2.html#example4[Ex 4 - Writing a Mixed Data File]
.... link:bbcfile2.html#example5[Ex 5 - Reading a Mixed Data File]
.... link:bbcfile2.html#example6[Ex 6 - Writing 'AT END' of Mixed Files]
... link:bbcfile2.html#compatible[Compatible Data Files]
.... link:bbcfile2.html#example7[Ex 7 - Writing a Compatible Data File]
.... link:bbcfile2.html#example8[Ex 8 - Reading a Compatible Data File]
.. link:bbcfile3.html#randomfiles[Random (Relative) FIles]
... link:bbcfile3.html#introduction[Introduction]
... link:bbcfile3.html#designing[Designing the File]
.... link:bbcfile3.html#structure[Record Structure]
.... link:bbcfile3.html#accessing[Accessing The Records]
... link:bbcfile3.html#example9[Ex 9 - Simple Random Access File]
... link:bbcfile3.html#example10[Ex 10 - Simple Random Access Database]
... link:bbcfile3.html#example11[Ex 11 - Random Access Inventory Program]
.. link:bbcfile4.html#indexed[Indexed Data Files]
... link:bbcfile4.html#deficiencies[Deficiencies of Random Access Files]
... link:bbcfile4.html#addressbook[The Address Book Program]
.... link:bbcfile4.html#fileorg[File Organisation]
.... link:bbcfile4.html#progorg[Program Organisation]
.... link:bbcfile4.html#index[The Index]
... link:bbcfile4.html#example12[Ex 12 (the LAST)]
.. link:bbcfile4.html#binarychop[The Binary Chop]
... link:bbcfile4.html#explanation[Explanation]

[upperalpha]
. *link:annexa.html[Table of ASCII Codes]*
. *link:annexb.html[Mathematical Functions]*
. *link:annexc.html[Error Messages and Codes]*
.. link:annexc.html#summary[Summary]
... link:annexc.html#trapprog[Trappable - Program]
... link:annexc.html#trapos[Trappable - Operating System]
... link:annexc.html#untrap[Untrappable - Error Code 0]
.. link:annexc.html#details[Details]
... link:annexc.html#accuracylost[Accuracy lost]
... link:annexc.html#arguments[Arguments]
... link:annexc.html#array[Array]
... link:annexc.html#badcall[Bad call]
... link:annexc.html#badcommand[Bad command]
... link:annexc.html#baddim[Bad DIM]
... link:annexc.html#badhex[Bad HEX]
... link:annexc.html#badname[Bad name]
... link:annexc.html#badprogram[Bad program]
... link:annexc.html#badstring[Bad string]
... link:annexc.html#cantmatchfor[Can't match FOR]
... link:annexc.html#channel[Channel]
... link:annexc.html#closeerror[Close error]
... link:annexc.html#dimspace[DIM space]
... link:annexc.html#directoryfull[Directory full]
... link:annexc.html#diskfull[Disk full]
... link:annexc.html#divisionbyzero[Division by zero]
... link:annexc.html#escape[Escape]
... link:annexc.html#exprange[Exp range]
... link:annexc.html#failedatnnn[Failed at nnn]
... link:annexc.html#fileexists[File exists]
... link:annexc.html#filenotfound[File not found]
... link:annexc.html#forvariable[FOR variable]
... link:annexc.html#linespace[LINE space]
... link:annexc.html#logrange[Log range]
... link:annexc.html#missingcomma[Missing ,]
... link:annexc.html#missingquote[Missing "]
... link:annexc.html#missingbracket[Missing )]
... link:annexc.html#missinghash[Missing #]
... link:annexc.html#mistake[Mistake]
... link:annexc.html#negativeroot[-ve root]
... link:annexc.html#nogosub[No GOSUB]
... link:annexc.html#nofn[No FN]
... link:annexc.html#nofor[No FOR]
... link:annexc.html#noproc[No PROC]
... link:annexc.html#norepeat[No REPEAT]
... link:annexc.html#noroom[No room]
... link:annexc.html#nosuchfnproc[No such FN/PROC]
... link:annexc.html#nosuchline[No such line]
... link:annexc.html#nosuchvariable[No such variable]
... link:annexc.html#noto[No TO]
... link:annexc.html#notlocal[Not LOCAL]
... link:annexc.html#onrange[ON range]
... link:annexc.html#onsyntax[ON syntax]
... link:annexc.html#outofdata[Out of DATA]
... link:annexc.html#outofrange[Out of range]
... link:annexc.html#renumberspace[RENUMBER space]
... link:annexc.html#silly[Silly]
... link:annexc.html#stringtoolong[String too long]
... link:annexc.html#subscript[Subscript]
... link:annexc.html#syntaxerror[Syntax error]
... link:annexc.html#toobig[Too big]
... link:annexc.html#toomanyopenfiles[Too many open files]
... link:annexc.html#typemismatch[Type mismatch]
. *link:annexd.html[Format of Program and Variables in Memory]*
.. link:annexd.html#memorymap[Memory Map]
... link:annexd.html#memorymap[The Memory Map]
.. link:annexd.html#management[Memory Management]
... link:annexd.html#limiting[Limiting the Number of Variables]
... link:annexd.html#stringmanage[String Management]
.... link:annexd.html#garbage[Garbage Generation]
.... link:annexd.html#stringallocation[Memory Allocation for String Variables]
.. link:annexd.html#programstorage[Program Storage in Memory]
... link:annexd.html#linelength[Line Length]
... link:annexd.html#linenumber[Line Number]
... link:annexd.html#statements[Statements]
... link:annexd.html#terminator[Line Terminator]
.. link:annexd.html#variablestorage[Variable Storage in Memory]
... link:annexd.html#integer[Integer Variables]
... link:annexd.html#real[Real Variables]
... link:annexd.html#string[String Variables]
... link:annexd.html#fixedstrings[Fixed Strings]

